# Generated by Django 3.2.7 on 2021-10-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='service', to='myapp.Headingservice'),
        ),
    ]
