# Generated by Django 3.2.7 on 2021-10-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_service_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='descripstion',
            field=models.TextField(default='description here'),
        ),
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.ImageField(default='img.png', upload_to='Works/'),
        ),
    ]
