# Generated by Django 3.2.7 on 2021-10-26 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211027_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='descripstion',
            new_name='description',
        ),
    ]
