# Generated by Django 3.2.7 on 2021-10-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_descripstion_work_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='work_list',
            field=models.ManyToManyField(blank=True, related_name='work_list', to='myapp.Work'),
        ),
    ]
