# Generated by Django 3.2.7 on 2021-10-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField(verbose_name=2014)),
                ('group', models.CharField(max_length=30)),
                ('org', models.CharField(max_length=200)),
                ('hpa', models.FloatField(default=5.0)),
            ],
        ),
    ]
