# Generated by Django 3.2.7 on 2021-10-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='year',
            new_name='year_name',
        ),
    ]
