# Generated by Django 3.2.7 on 2021-10-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_year_education_year_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='year_name',
            field=models.IntegerField(default=2014),
        ),
    ]
