# Generated by Django 3.2.7 on 2021-10-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_education_year_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mycareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.IntegerField(default=2)),
                ('projects', models.IntegerField(default=2)),
                ('award', models.IntegerField(default=2)),
                ('experience', models.IntegerField(default=2)),
            ],
        ),
    ]
