# Generated by Django 3.2.7 on 2021-10-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_mycareer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('phone_1', models.CharField(max_length=11)),
                ('phone_2', models.CharField(max_length=11)),
                ('email_1', models.EmailField(max_length=40)),
                ('email_2', models.EmailField(max_length=40)),
            ],
        ),
    ]
