# Generated by Django 3.2.7 on 2021-10-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socaillink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instragam', models.URLField(blank=True)),
                ('likedin', models.URLField(blank=True)),
                ('skype', models.URLField(blank=True)),
            ],
        ),
    ]
